### ISSUE TITLE
Error running command: python deobfuscator.py 

### ISSUE THREAD

**Issue by ghost** [giacomoferretti/paranoid-deobfuscator#1]
I obtain the following error:
python: can't open file ...  [Errno 2] No such file or directory

With command:
python deobfuscator.py  path of directory output of apktool

How to solve it?

**Comment by giacomoferretti** [comment]
Could you provide a more detailed log? (strip anything sensitive)

I suppose you are in the same directory of the `deobfuscator.py` script.
