### ISSUE TITLE
Obfuscated apps?

### ISSUE THREAD

**Issue by Progress1** [giacomoferretti/paranoid-deobfuscator#2]
Is it possible modify **search_deobfuscator_class** that it works on obfuscated apps? (not searching fixed names). Or maybe add some additional parameters where we can specify what to do? :)

**Comment by giacomoferretti** [comment]
It should already work with obfuscated apps, the matching algorithm it's pretty simple so it can produce a lot a false positives. I could add a parameter to specify the class to use like you said.

I haven't touch this project for like 9 months, I need to read it :sweat_smile:

**Comment by Progress1** [comment]
:-) check email, i send you 21.5 some example

**Comment by giacomoferretti** [comment]
Looked into it and realized there is no support for multiple entries in the obfuscated String array, but only one obfuscated string.
Also rewrote the search for the obfuscated string and getString signature.

I'm gonna test it some more and when it's ready I'll push the fixes.

**Comment by giacomoferretti** [comment]
Can you tell me if it works now?

**Comment by giacomoferretti** [comment]
Ok, try now. It should work.

**Comment by Progress1** [comment]
I try first release.zip but there was error. Then i find that in repository is probably newer version (difference in .py and .jar) I try this but error was the same :
```
Traceback (most recent call last):
  File "deobfuscator.py", line 207, in <module>
    main(args)
  File "deobfuscator.py", line 111, in main
    deobfuscator_class, encrypted_strings = deobfuscator.search_deobfuscator_class(path)
  File "deobfuscator.py", line 78, in search_deobfuscator_class
    if self.get_deobfuscator_signature(os.path.join(root, filename)):
  File "deobfuscator.py", line 91, in get_deobfuscator_signature
    method_class = file.split('smali')[1].split('/', 1)[1][:-1]
IndexError: list index out of range
```

I can send you decoded example for testing purposes (.rar, ~85MB)

**Comment by giacomoferretti** [comment]
Uh, that's strange. If you send me the rar I'll appreciate it.

**Comment by Progress1** [comment]
Check your email

**Comment by giacomoferretti** [comment]
It seems like you are using Windows and I only tested it on Linux. Try replacing ```'/'``` with ```'\'```

**Comment by Progress1** [comment]
I don't send any '/' char to commandline. I execute: python.exe deobfuscator.py dir_name.
dir_name it's just name without path. If i use full path to dir_name, also with replaced '/' - it's the same.

Maybe use os.path? os.sep - separator

Edit 2: if i change it to '\\' it doesn't crash, app normally exit and doesn't make any changes.

**Comment by giacomoferretti** [comment]
Yes, `os.sep` it's a good suggestion. Tried your app (2.2.0) on Fedora 34 and didn't have any problem. I'm now trying on Windows.

**Comment by giacomoferretti** [comment]
Ok, tested and should work now.

**Comment by Progress1** [comment]
One small issue, check email ;-)
