### ISSUE TITLE
Support deobfuscation of dexes

### ISSUE THREAD

**Issue by komen205** [giacomoferretti/paranoid-deobfuscator#8]
Hello,

It is possible for the python support deobfuscation of dexes? It would be needed to convert the dex to smali. This helps in packed applications.

Let me know, maybe I can help integrate if you need.

**Comment by giacomoferretti** [comment]
Should work now, added support in 3412ec507a6c15883caf93fba8fc55d3b18a7602.

You need to run `baksmali` first and the run `python -m paranoid_deobfuscator` on the output directory.
